name: odata
description: >
  This library is an abstraction of a client to make OData requests, intended to make the process of learning and using OData resources easier.
version: 1.0.3
homepage: https://github.com/danielbom/odata.dart

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  http: ^0.13.3

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.17.12
